# permissions for end users to edit nodedeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodedeployment-editor-role
rules:
- apiGroups:
  - edge.harmonycloud.cn
  resources:
  - nodedeployments
  - nodemaintenances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edge.harmonycloud.cn
  resources:
  - nodedeployments/status
  - nodemaintenances/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
