# permissions for end users to view nodedeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodedeployment-viewer-role
rules:
- apiGroups:
  - edge.harmonycloud.cn
  resources:
  - nodedeployments
  - nodemaintenances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edge.harmonycloud.cn
  resources:
  - nodedeployments/status
  - nodemaintenances/status
  verbs:
  - get
